host = "0.0.0.0"
port = 3000
db_path = "./data/emit_hub.redb"
max_connections_per_channel = 5000
log_level = "debug"

[cors]
allowed_origins = ["*"]
max_age = 7200

[websocket]
connection_timeout = 60
ping_interval = 45

[persistence]
persist_messages_default = true
message_retention_days = 90
auto_backup = true